### ISSUE TITLE
PDF link

### ISSUE THREAD

**Issue by Mrc527** [rafalab/dsbook-part-2#1]
Hello,

The PDF link is pointing to the part-1, the “Introduction to Data Science” book.

I could not find the PDF for this one.

**Comment by aosaf-e-c** [comment]
Hi! I think there is only a single pdf version containing both part 1 and part 2 of the book. If you download the pdf version, you can find "Part III Statistics with R" from page 241 which I essentially believe is part 2 of the online version

**Comment by rafalab** [comment]
aosaf-e-c is correct. Currently, the only PDF that is available is an old version that combines both parts.

Note that, although not straight-forward, you can build the PDF by downloading all the quarto files and rendering. In a terminal window you would type:

```
git clone https://github.com/rafalab/dsbook-part-2.git
cd dsbook-part-2
quarto render --to-pdf
```

You will need to install all packages including **tinytex**, used in the book for this to work.
