### ISSUE TITLE
Chapter 15, Section 15.2.  Did I miss something?

### ISSUE THREAD

**Issue by jcornickm** [rafalab/dsbook-part-2#17]
The next to last paragraph in this sections indicates "The plot we just made, using summarize and tidy...".  What plot? tidy was used previously, but not summarize, and no plot was made in this section.  I thought perhaps you were referring to the plots in section 15.1, but "summarize" was not used to create them.

Rafa:  no need to respond.  If this is useful for you, as you work on the text, great.  If not, ignore it.

**Comment by rafalab** [comment]
Removed that paragraph (was left from old version). Thanks!
