### ISSUE TITLE
Section 15.4.1: can't follow

### ISSUE THREAD

**Issue by jcornickm** [rafalab/dsbook-part-2#19]
Hello Rafa.  Just to be clear:  I write to report a difficulty other readers may be experiencing, and which you might take into account for future editions of IDS (part 2).  I am NOT writing expecting you the problem I will report (I understand you are not my tutor).

I simply can´t follow the section.

Step 1 is easy enought:  you run a regression of runs on all plays with data up to 2001:

Step 2:  you calculate the average team plate appeareces per game in 2002 (pa_per_game).

Step 3:  you indicate that ppa will be computed for players available in 2002, but I don´t see anywhere a filter so that only those players are taken into account.

But the calculation of g is what really throws me off:  g = sum(pa)/pa_per_game.

The thing is:  sum(pa) may vary acrross players of similar ability if some played more years than others, so what sense does it make to compare it between someone who played, say, ten years, and someone who played only two?  And then that is divided by pa_per_game, which was calculated using data only for 2022?

It may be very well my fault, but I have been working at this for several hours, and can´t make heads or tails of it, but I thought I would let you know, just in case at least part of the fault lies with the text itself.

Best regards, JC

**Comment by rafalab** [comment]
Thanks. This will help with the rewrite.
