### ISSUE TITLE
Hierarchical Models 13.3 missing "2 times"?

### ISSUE THREAD

**Issue by BruciiZ** [rafalab/dsbook-part-2#20]
<img width="760" alt="image" src="https://github.com/user-attachments/assets/404b90aa-40e9-4daf-8b88-de5e5ff3243f">

Should the notation here be  $X_j \sim \mbox{N}\left(\mu, 2 \sqrt{p(1-p)/N}\right)$ since it is the standard error of 2p-1?

**Comment by rafalab** [comment]
Yes! It is fixed and will appear after the next push of the html book.
