### ISSUE TITLE
Code error - 20.9 Indexing with matrices - second code block

### ISSUE THREAD

**Issue by rob-works** [rafalab/dsbook-part-2#21]
There's a coding error on [https://rafalab.dfci.harvard.edu/dsbook-part-2/highdim/matrices-in-R.html#indexing-with-matrices](url)

The text reads, "A useful application of this approach is that we can change all the `NA` entries of a matrix to something else:"

But the accompanying code is:

`x[!is.na(x)] <- 0`

I believe it should be:
`x[is.na(x)] <- 0`

As the code given would convert every non NA value to 0.

**Comment by rafalab** [comment]
Thanks! Will be fixed in the next push.
