### ISSUE TITLE
Chapter 12 Bayesian Statistics - inconsistency of sigma

### ISSUE THREAD

**Issue by BruciiZ** [rafalab/dsbook-part-2#22]
The book has:

standard error :

$$
\mbox{SE}(\mu \mid \bar{X})^2 = \frac{1}{1/\sigma^2+1/\tau^2}.
$$ 

 _To compute a posterior distribution and construct a credible interval, we define a prior distribution with mean 0% and standard error 3.5%, which can be interpreted as follows: before seeing polling data, we don't think any candidate has the advantage, and a difference of up to 7% either way is possible. We compute the posterior distribution using the equations above:_

```{r}
theta <- 0
tau <- 0.035
sigma <- results$se
x_bar <- results$avg
B <- sigma^2 / (sigma^2 + tau^2)

posterior_mean <- B*theta + (1 - B)*x_bar
posterior_se <- sqrt(1/(1/sigma^2 + 1/tau^2))

posterior_mean
posterior_se
```

From this line of code: `B <- sigma^2 / (sigma^2 + tau^2)`, we know that `sigma` is defined as $\sqrt{\sigma^2 / n}$, then isn't it wrong to use `sigma` for `posterior_se <- sqrt(1/(1/sigma^2 + 1/tau^2))`?

**Comment by rafalab** [comment]
Thanks. This will be fixed soon.
