### ISSUE TITLE
Probable typo in code block

### ISSUE THREAD

**Issue by biscotty666** [rafalab/dsbook-part-2#4]
http://rafalab.dfci.harvard.edu/dsbook-part-2/prob/discrete-probability.html#monte-carlo-example

```
(hands[1] %in% aces & hands[2] %in% facecard) | 
  (hands[2] %in% aces & hands[1] %in% facecard)
#> [1] FALSE
```
I'm almost certain that `hand` and not `hands` is what is meant.

Thank you for the wonderful book.

**Comment by rafalab** [comment]
Thanks for finding and reporting this. I have made the change locally and will push to GitHub soon.
