### ISSUE TITLE
Chapter 9, exercise 4

### ISSUE THREAD

**Issue by jcornickm** [rafalab/dsbook-part-2#6]
We are asked to generate a sample of size N from an urn with 52% blue beads.  The code provided is as follows:

    N <- 1000 
    p <- 0.52
    x <- rbinom(N, 1, 0.5)

This is drawing a sample from a population with 50% blue beads.  The correct code would be either

    x <- rbinom(N,1,p)  

or
   
  x <-rbinom(N,1,0.52)

Am I mistaken?

**Comment by rafalab** [comment]
This was an error. it should be `x <-rbinom(N,1,p)`

It is fixed now.

**Comment by jcornickm** [comment]
Thanks so much. Merry Christmas!

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by jcornickm** [comment]
Rafa:

I just saw your acknowledgement in the introduction to your book (part 2).  Wow!  Many thanks.  I am still working through the book (who could go back to being a full time student?), but this made may day.

My name, by the way, is Jorge Cornick.

***@***.***

**Comment by rafalab** [comment]
Added your name! 

Thank you, Jorge. Your comments have really helped me improve the book.
