### ISSUE TITLE
Misplaced(?) paragraph in §15.2 ("the broom package")

### ISSUE THREAD

**Issue by SydneyUni-Jim** [rafalab/dsbook-part-2#7]
Is the paragraph quoted below from [§15.2 ("the broom package")](https://rafalab.dfci.harvard.edu/dsbook-part-2/linear-models/multivariate-regression.html#the-broom-package) misplaced? Up to this point I don't think there's been any mention of determining if slopes changed. And there doesn't seem to be a plot showing overlapping confidence intervals.

> Now we return to discussing our original task of determining if slopes changed. The plot we just made, using summarize and tidy, shows that the confidence intervals overlap, which provides a nice visual confirmation that our assumption that the slope does not change is safe.

**Comment by rafalab** [comment]
That paragraph has been removed. thanks!
